easy_admin:
    site_name: 'ProjetS4'
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        UserAdmin:
            class: AppBundle\Entity\UserAdmin
            list:
                fields: ['id', 'username', 'email', 'enabled', 'lastLogin', 'roles','elo', 'imageName', 'updatedAt']
                sort: ['id', 'ASC']
            form:
                fields: ['username', 'email', 'roles', 'elo', 'rank', { property: 'imageFile', type: 'vich_image' }]
                sort: ['id', 'ASC']
            disabled_actions: ['new']
        Carte:
          class: AppBundle\Entity\Carte
          list:
              fields: ['id', 'valeur', 'imageName', 'updatedAt']
              sort: ['id', 'ASC']
          form:
              fields: ['valeur', { property: 'imageFile', type: 'vich_image' }]
              sort: ['id', 'ASC']
        Objectif:
            class: AppBundle\Entity\Objectif
            list:
                fields: ['id', 'valeur', 'imageName', 'updatedAt']
                sort: ['id', 'ASC']
            form:
                fields: ['valeur', { property: 'imageFile', type: 'vich_image' }]
                sort: ['id', 'ASC']
        Partie:
            class: AppBundle\Entity\Partie
            list:
                fields: ['id', {property: 'joueur1.username', label: 'Joueur 1'}, {property: 'joueur2.username', label: 'Joueur 2'}, 'manche', 'winner', 'ended']
                sort: ['id', 'ASC']
            form:
                fields: ['joueur1', 'joueur2', 'manche', 'winner']
                sort: ['id', 'ASC']
            disabled_actions: ['new']
    design:
        menu:
            - { label: 'Accueil', route: 'homepage', icon: 'home' }
            - { entity: 'UserAdmin', label: 'Utilisateurs', icon: 'user' }
            - { entity: 'Partie', label: 'Parties', icon: 'th-large' }
            - { entity: 'Carte', label: 'Cartes', icon: 'th-large' }
            - { entity: 'Objectif', label: 'Objectif', icon: 'th-large' }
        brand_color: '#333333'