easy_admin:
    site_name: 'Administration'
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        UserAdmin:
            class: AppBundle\Entity\UserAdmin
            list:
                fields: ['id', 'username', 'email', 'enabled', 'lastLogin', 'roles','elo', 'imageName', 'updatedAt']
                sort: ['lastLogin', 'DESC']
            form:
                fields: ['username', 'email', 'roles', 'elo', 'rank', 'apiKey', { property: 'imageFile', type: 'vich_image' }]
                sort: ['lastLogin', 'DESC']
            disabled_actions: ['new']
        Partie:
            class: AppBundle\Entity\Partie
            list:
                fields: ['id', {property: 'joueur1.username', label: 'Joueur 1'}, {property: 'joueur2.username', label: 'Joueur 2'}, 'manche', 'winner']
                sort: ['id', 'DESC']
            form:
                fields: ['joueur1', 'joueur2', 'manche', 'winner']
                sort: ['id', 'DESC']
            disabled_actions: ['new']
        Message:
            class: AppBundle\Entity\Message
            list:
                fields: ['id', 'contenu', {property: 'partie', label: 'partie'}, {property: 'joueur.username', label: 'auteur'}, 'createdAt']
                sort: ['id', 'DESC']
            form:
                fields: ['contenu']
            new:
                fields: ['contenu', {property: 'partie', label: 'partie'}, {property: 'joueur', label: 'auteur'}]
    design:
        menu:
            - { label: 'Accueil', route: 'homepage', icon: 'home' }
            - { entity: 'UserAdmin', label: 'Utilisateurs', icon: 'user' }
            - { entity: 'Partie', label: 'Parties', icon: 'gamepad' }
            - { entity: 'Message', label: 'Messages', icon: 'comment' }
        brand_color: '#333333'